<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <Nullable>enable</Nullable>
    <WarningsAsErrors>nullable</WarningsAsErrors>
    <ImplicitUsings>disable</ImplicitUsings>

    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>CatNip.Domain</PackageId>
    <Version>4.1.0</Version>
    <Authors>Dimitrie Tataru</Authors>
    <Company>A C E</Company>
    <Description>Clean Architecture Template - Domain Abstractions</Description>
    <PackageTags>clean;architecture;template;domain;abstractions</PackageTags>
  </PropertyGroup>

  <ItemGroup Condition="'$(Configuration)' == 'Debug'">
    <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="10.0.301">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
