name: build-CI

on:
  push:
    branches:
    - ace
    - main
    - develop
    - feature/**
    - bugfix/**
    tags-ignore:
      - '**'
    paths-ignore:
      - 'README.md'

jobs:
  build:

    env:
      CONFIG: 'Release'
      SOLUTION: 'src/CatNip.Domain.sln'

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x
        cache: true
        cache-dependency-path: '**/*.csproj'

    - name: dotnet restore
      run: dotnet restore $SOLUTION

    - name: dotnet build
      run: dotnet build $SOLUTION --configuration $CONFIG --no-restore
